version: '3.8'
      
services:
  elk:
    image: "sebp/elk"
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    networks:
      - elk_net

networks:
  elk_net:
    driver: bridge